import { db } from "./db";
import {
  createConversation,
  getConversation,
  getAllConversations,
  getConversationsWithMessages,
  updateConversation,
  deleteConversation,
  addMessage,
  getMessages,
  updateMessage,
  getConversationWithMessages,
  getOrCreateConversation,
  DEFAULT_PROJECT_ID,
  DEFAULT_PROJECT_NAME,
  getProject,
  listProjects,
  createProject,
  deleteProject,
  ensureDefaultProject,
  listProjectFiles,
  getProjectFile,
  upsertProjectFile,
  deleteProjectFile,
  getConversationProject,
  setConversationProject,
  setConversationPermissionMode,
} from "./queries";

// Re-export db and all query functions
export {
  db,
  createConversation,
  getConversation,
  getAllConversations,
  getConversationsWithMessages,
  updateConversation,
  deleteConversation,
  addMessage,
  getMessages,
  updateMessage,
  getConversationWithMessages,
  getOrCreateConversation,
  DEFAULT_PROJECT_ID,
  DEFAULT_PROJECT_NAME,
  getProject,
  listProjects,
  createProject,
  deleteProject,
  ensureDefaultProject,
  listProjectFiles,
  getProjectFile,
  upsertProjectFile,
  deleteProjectFile,
  getConversationProject,
  setConversationProject,
  setConversationPermissionMode,
};
